server {
  listen 80;
  listen [::]:80;
  server_name game.geoflux.ru;

  root /var/www/game/client/dist;
  index index.html;

  location /.well-known/acme-challenge/ {
    try_files $uri =404;
  }

  location /ws {
    proxy_pass http://127.0.0.1:3101;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering off;
  }

  location /game/ {
    proxy_pass http://127.0.0.1:3100/;
  }

  location /auth/ {
    proxy_pass http://127.0.0.1:3200/;
  }

  location /blockchain/ {
    proxy_pass http://127.0.0.1:3300/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
